### ISSUE TITLE
how to build????

### ISSUE THREAD

**Issue by c0d3rb0y** [StylexTV/HyCheat#2]
# How do i build?
Just wondering how i build my custom version...
Didn't see a license, so i used some of the stuff.
Also, was that ok to use the stuff?
# How close to done is it?
Progress bars:
[===>------] I have finished
[----------] I have built it

**Comment by StylexTV** [comment]
Hey, sorry for the late answer but for some reason Github didn't notify me about your issue or your pull request...

I usually build the project with the forge mdk and intellij (send me a message if you need more information, idk).
I have merged your pull request with the improved readme. Thank you for that 👍 

And I also saw that you have updated the mod to 1.16 and have also added some other cool stuff.
Let me now when you are done, cause I would love to merge that too :D

**Comment by c0d3rb0y** [comment]
nice, still working on changing some functions over.

**Comment by c0d3rb0y** [comment]
Working on a added module for BedWars. Basically it'll add Glow to all the other players.

Haven't pushed it to my own branch yet. Might be awhile.
